### ISSUE TITLE
Add derpconf support

### ISSUE THREAD

**Issue by deurk** [thumbor-community/prometheus#17]
Hello,

thumbor supports [derpconf](https://github.com/globocom/derpconf) to allow for ENVIRONMENT VARIABLES override of configured variable. Would it be possible to add this for the configuration of `PROMETHEUS_SCRAPE_PORT` ?

Thanks !

**Comment by savar** [comment]
the `PROMETHEUS_SCRAPE_PORT` is being taken out of a `config` object which is passed through from thumbor to the plugins, therefore this is already working as you want it to work. Simply do this:

```sh
PROMETHEUS_SCRAPE_PORT=8009 thumbor --use-environment 1 -c thumbor.conf
```

afterwards you can call it via:

```sh
curl -s http://localhost:8009/prometheus | head -n 3
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 466.0
```

I am closing this issue. In case you have any other issue with that, please re-open it.
