### ISSUE TITLE
Versioning tag

### ISSUE THREAD

**Issue by fmunteanu** [thumbor-community/prometheus#2]
Please add a version tag, so we can download and properly package the software.

**Comment by fmunteanu** [comment]
Hi @Savar can you please implement a version tag? Thank you.

**Comment by Savar** [comment]
Uh.. I somehow missed your comment 11days ago.. let me check your request.

**Comment by Savar** [comment]
@fmunteanu please check if this is what you wanted (tag 0.1.1)

**Comment by fmunteanu** [comment]
Thank you!
