### ISSUE TITLE
Cannot run multiple instances without workaround

### ISSUE THREAD

**Issue by slothentic** [thumbor-community/prometheus#3]
Hi there, I ended up writing a bit of code to workaround the issue of only being able to run one instance of thumbor:

```
METRICS = 'tc_prometheus.metrics.prometheus_metrics'

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-p', '--port')
parser.add_argument('-c', '--conf')
args = parser.parse_args()
current_port_plus_1000 = int(args.port) + 1000

PROMETHEUS_SCRAPE_PORT = current_port_plus_1000
```

It would be great to see this plugin update to do something like this. Currently when you run multiple instance of thumbor on different ports only the first instance works because it gets the error `[Errno 98] Address already in use`

This small workaround just adds 1000 to the current port, so if you are running thumbor on 8000-8003 the respective ports would serve the prometheus metrics on ports 9000-9003

**Comment by frisi** [comment]
the same problem hit me when using thumbor metrics with MinimalCompact/thumbor: https://github.com/MinimalCompact/thumbor/issues/92

in this case a solution to unify the metrics for all instances started within the docker image would be more practical because the docker image exposes the thumbor processes on a single port. so i believe metrics should do the same.

**Comment by savar** [comment]
Sorry for the late reply. I am not sure if it makes sense to dynamically change the port. Your workaround already did that but even thumbor is not able to do that (the minimalcompact/thumbor is using `--fd` and is being configured from the outside, it could do the same by specifying the environment variable for the prometheus port).

Also using this means also you might want to check https://github.com/MinimalCompact/thumbor/issues/92 and follow kkopachev's advice and use the prometheus_statsd_exporter and use the statsd metrics from thumbor.

If you still think it make sense to create a feature as initially suggested, we should discuss that further..

**Comment by savar** [comment]
I will close this issue for now. In case you still want to check up on that, please re-open it.
