### ISSUE TITLE
Thumbor 7 Compatibility

### ISSUE THREAD

**Issue by heynemann** [thumbor-community/prometheus#4]
Hey would you be willing to work together to update this to thumbor 7? 

For more information on what changed you can check the release at https://github.com/thumbor/thumbor/releases/tag/7.0.0

**Comment by heynemann** [comment]
Hey @savar would love to help here! This is a great addition to thumbor's ecosystem!

Great job BTW! Adding this to awesome thumbor!

**Comment by savar** [comment]
Hey @heynemann I didn't realize your message from 16 days ago, I am sorry about that. I am swamped with other work right now and I am not sure if I can do anything here at the moment. Feel free to either do it yourself (I gave you admin rights, even though you "had" them anyways ;) ) or wait a bit and I'll try to come back to this one.
