### ISSUE TITLE
Thumbor 7 uses identical names for counters and timeseries and it causes exception in Prometheus registry

### ISSUE THREAD

**Issue by mbarouski** [thumbor-community/prometheus#9]
I opened PR in Thumbor project https://github.com/thumbor/thumbor/pull/1462 to fix this.
If it's not merged, then this project should add different postfixes for counters and time series metrics.
Hope it will be merged, then we will have to put restriction on Thumbor version like >=7.0.11 (current 7.0.10) or something similar.
@savar maybe you have other thoughts to fix this?

**Comment by savar** [comment]
As I can see, you face more than one of these issues and checking the statsd->prometheus exporter this is a known issue: https://github.com/prometheus/statsd_exporter#explicit-metric-type-mapping

So I guess it might make sense for the time being (even though it is not nice) to create a mapping. Additionally it might make sense to support extra config similar to the exporter but that would make it much more complicated and error prone.

![image](https://user-images.githubusercontent.com/246341/178111330-a7796770-b0c4-400c-a141-5cd189665155.png)
as we can see we have exactly the 3 broken ones here.. `none_smart`, `smart` and `image.fetch` which already is decoded to use labels. So we could treat this one even more special and add to them all in `incr()` a postfix `_total`. That would be my only Idea right now.
WDYT?

**Comment by mbarouski** [comment]
@savar I initially thought to add postfixes to both, but `timing` metrics are not always about latency, so adding of  postfix to `incr` metrics only is nice by me 👍🏻

**Comment by mbarouski** [comment]
BTW to do with the postfix changes... `original_image.status` metric has one more label `networklocation` (it's optional) that is not in specified in the map in master branch.

**Comment by savar** [comment]
@mbarouski can we close this issue for now or do you want to keep it open?

**Comment by mbarouski** [comment]
@savar sure, we can close it
